package com.acacia.platform

import com.acacia.generator.KotlinGenerator
import com.acacia.model.ModifierFunction
import com.squareup.kotlinpoet.*
import org.gradle.api.Project
import java.io.File

/**
 * Platform-aware code generator for cross-platform Compose DSL.
 */
class PlatformCodeGenerator(private val project: Project) {
    
    private val platformDetector = PlatformDetector(project)
    private val unifiedNamingEngine = UnifiedNamingEngine(project)
    private val baseGenerator = KotlinGenerator()
    
    /**
     * Generates platform-aware DSL code.
     */
    fun generatePlatformDsl(
        functions: List<ModifierFunction>,
        outputDir: File
    ): File {
        val platform = platformDetector.detectPlatform()
        
        project.logger.lifecycle("Shortify: Generating platform-aware DSL for ${platform.name}")
        
        // Generate unified name mappings
        val nameMappings = unifiedNamingEngine.generateUnifiedShortNames(functions)
        
        // Build platform-specific file spec
        val fileSpec = buildPlatformFileSpec(functions, nameMappings, platform)
        
        outputDir.mkdirs()
        fileSpec.writeTo(outputDir)
        
        return File(outputDir, "ShortModifiers.kt")
    }
    
    /**
     * Builds platform-specific file specification.
     */
    private fun buildPlatformFileSpec(
        functions: List<ModifierFunction>,
        nameMappings: Map<String, String>,
        platform: PlatformDetector.Platform
    ): FileSpec {
        val packageName = "com.acacia.generated"
        val fileName = "ShortModifiers"
        
        return FileSpec.builder(packageName, fileName)
            .addFileComment("Generated by Acacia Shortify Plugin")
            .addFileComment("Platform: ${platform.name}")
            .addFileComment("DO NOT EDIT - This file is generated automatically")
            .apply {
                // Add platform-specific imports
                val platformImports = unifiedNamingEngine.getPlatformImports(platform)
                platformImports.forEach { import ->
                    addImport(import)
                }
                
                // Add functions sorted by name
                functions.sortedBy { it.name }.forEach { function ->
                    val shortName = nameMappings[function.name] ?: function.name
                    addFunction(buildPlatformFunction(function, shortName, platform))
                }
            }
            .build()
    }
    
    /**
     * Builds platform-specific function specification.
     */
    private fun buildPlatformFunction(
        function: ModifierFunction,
        shortName: String,
        platform: PlatformDetector.Platform
    ): FunSpec {
        val modifierClassName = platformDetector.getModifierClassName(platform)
        val documentation = unifiedNamingEngine.getPlatformDocumentation(function.name, platform)
        
        return FunSpec.builder(shortName)
            .receiver(ClassName.bestGuess(modifierClassName))
            .returns(ClassName.bestGuess(modifierClassName))
            .addKdoc(documentation)
            .apply {
                // Add parameters
                function.parameters.forEach { param ->
                    val parameterSpec = ParameterSpec.builder(
                        name = param.name,
                        type = parsePlatformTypeName(param.type, platform)
                    ).apply {
                        if (param.hasDefault && param.defaultValue != null) {
                            defaultValue(param.defaultValue)
                        }
                    }.build()
                    addParameter(parameterSpec)
                }
                
                // Generate function body
                val parameterNames = function.parameters.joinToString(", ") { it.name }
                addStatement("return this.%L(%L)", function.name, parameterNames)
            }
            .build()
    }
    
    /**
     * Parses type names for specific platforms.
     */
    private fun parsePlatformTypeName(type: String, platform: PlatformDetector.Platform): TypeName {
        return when (platform) {
            PlatformDetector.Platform.ANDROID -> parseAndroidTypeName(type)
            PlatformDetector.Platform.DESKTOP -> parseDesktopTypeName(type)
            PlatformDetector.Platform.WEB -> parseWebTypeName(type)
            PlatformDetector.Platform.IOS -> parseIosTypeName(type)
            PlatformDetector.Platform.UNKNOWN -> parseGenericTypeName(type)
        }
    }
    
    private fun parseAndroidTypeName(type: String): TypeName {
        return when (type) {
            "Dp" -> ClassName("androidx.compose.ui.unit", "Dp")
            "Color" -> ClassName("androidx.compose.ui.graphics", "Color")
            "PaddingValues" -> ClassName("androidx.compose.foundation.layout", "PaddingValues")
            "Boolean" -> ClassName("kotlin", "Boolean")
            "Int" -> ClassName("kotlin", "Int")
            "Float" -> ClassName("kotlin", "Float")
            "String" -> ClassName("kotlin", "String")
            else -> parseGenericTypeName(type)
        }
    }
    
    private fun parseDesktopTypeName(type: String): TypeName {
        return when (type) {
            "Dp" -> ClassName("androidx.compose.ui.unit", "Dp")
            "Color" -> ClassName("androidx.compose.ui.graphics", "Color")
            "PaddingValues" -> ClassName("androidx.compose.foundation.layout", "PaddingValues")
            "KeyEvent" -> ClassName("org.jetbrains.compose.desktop.ui", "KeyEvent")
            "Boolean" -> ClassName("kotlin", "Boolean")
            "Int" -> ClassName("kotlin", "Int")
            "Float" -> ClassName("kotlin", "Float")
            "String" -> ClassName("kotlin", "String")
            else -> parseGenericTypeName(type)
        }
    }
    
    private fun parseWebTypeName(type: String): TypeName {
        return when (type) {
            "Dp" -> ClassName("androidx.compose.ui.unit", "Dp")
            "Color" -> ClassName("androidx.compose.ui.graphics", "Color")
            "PaddingValues" -> ClassName("androidx.compose.foundation.layout", "PaddingValues")
            "MouseEvent" -> ClassName("org.w3c.dom.events", "MouseEvent")
            "Boolean" -> ClassName("kotlin", "Boolean")
            "Int" -> ClassName("kotlin", "Int")
            "Float" -> ClassName("kotlin", "Float")
            "String" -> ClassName("kotlin", "String")
            else -> parseGenericTypeName(type)
        }
    }
    
    private fun parseIosTypeName(type: String): TypeName {
        return when (type) {
            "Dp" -> ClassName("androidx.compose.ui.unit", "Dp")
            "Color" -> ClassName("androidx.compose.ui.graphics", "Color")
            "PaddingValues" -> ClassName("androidx.compose.foundation.layout", "PaddingValues")
            "Boolean" -> ClassName("kotlin", "Boolean")
            "Int" -> ClassName("kotlin", "Int")
            "Float" -> ClassName("kotlin", "Float")
            "String" -> ClassName("kotlin", "String")
            else -> parseGenericTypeName(type)
        }
    }
    
    private fun parseGenericTypeName(type: String): TypeName {
        val parts = type.split(".")
        return if (parts.size == 1) {
            ClassName("", type)
        } else {
            ClassName(parts.dropLast(1).joinToString("."), parts.last())
        }
    }
}
