package com.acacia.generator

import com.acacia.mapping.HybridNamingEngine
import com.acacia.model.ComposableFunction
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.asTypeName
import java.io.File

/**
 * Generates Kotlin code for short composable function wrappers using KotlinPoet.
 * Uses HybridNamingEngine for intelligent naming (Golden list + Algorithmic collision-free).
 */
class ComposableGenerator {

    private val namingEngine = HybridNamingEngine()

    // Type references for Compose types
    private val modifierClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.ui", "Modifier")
    private val dpClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.ui.unit", "Dp")
    private val colorClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.ui.graphics", "Color")
    private val shapeClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.ui.graphics", "Shape")
    private val arrangementClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.foundation.layout", "Arrangement")
    private val alignmentClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.ui", "Alignment")
    private val paddingValuesClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.foundation.layout", "PaddingValues")
    private val textStyleClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.ui.text", "TextStyle")
    private val fontWeightClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.ui.text.font", "FontWeight")
    private val textUnitClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.ui.unit", "TextUnit")
    private val painterClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.ui.graphics.painter", "Painter")
    private val imageVectorClassName = com.squareup.kotlinpoet.ClassName("androidx.compose.ui.graphics.vector", "ImageVector")
    private val composableAnnotation = com.squareup.kotlinpoet.ClassName("androidx.compose.runtime", "Composable")

    /**
     * Generates the ShortComposables.kt file containing all short composable wrapper functions.
     */
    fun generateShortComposables(
        functions: List<ComposableFunction>,
        outputDir: File
    ): File {
        // Reset naming engine for fresh collision tracking
        namingEngine.reset()

        val fileSpec = buildFileSpec(functions)

        outputDir.mkdirs()
        val file = File(outputDir, "ShortComposables.kt")
        file.writeText(fileSpec.toString())

        return file
    }

    private fun buildFileSpec(functions: List<ComposableFunction>): FileSpec {
        val fileBuilder = FileSpec.builder("com.acacia.generated", "ShortComposables")
            .addFileComment("Generated by Acacia Shortify Plugin")
            .addFileComment("\nDO NOT EDIT - This file is generated automatically")
            .addFileComment("\nNaming: 50 Golden (handcoded) + Algorithmic (auto) with collision detection")

        // Add imports for commonly used types
        fileBuilder.addImport("androidx.compose.foundation.layout", "Column", "Row", "Box", "Spacer", "Arrangement")
        fileBuilder.addImport("androidx.compose.ui", "Modifier", "Alignment")
        fileBuilder.addImport("androidx.compose.material3", "Text", "Button", "Card")

        // Only generate safe, known-good composable functions to avoid conflicts and errors
        val safeFunctions = functions.filter { function ->
            // Only include basic layout and UI composables that work well
            val safeFunctionNames = setOf(
                "Column", "Row", "Box", "Spacer"
            )
            safeFunctionNames.contains(function.name) && 
            !function.name.contains("-") && 
            !function.name.contains("_") &&
            // Only include functions with safe parameter types
            function.parameters.all { param ->
                param.type in setOf("Modifier", "String", "Int", "Float", "Boolean", "Dp", "Color", "TextStyle", "Alignment", "Arrangement", "PaddingValues")
            }
        }

        // Generate functions sorted by name for determinism
        safeFunctions.sortedBy { it.name }.forEach { function ->
            val shortName = namingEngine.generateComposableShortName(function)
            val funSpec = buildFunctionSpec(function, shortName)
            fileBuilder.addFunction(funSpec)
        }

        return fileBuilder.build()
    }

    private fun buildFunctionSpec(function: ComposableFunction, shortName: String): FunSpec {
        val funBuilder = FunSpec.builder(shortName)
            .addAnnotation(
                AnnotationSpec.builder(composableAnnotation)
                    .build()
            )
            .addKdoc("Short DSL wrapper for [${function.name}]")
            .addModifiers(KModifier.INLINE)

        // Add parameters
        function.parameters.forEach { param ->
            val paramSpec = buildParameterSpec(param)
            funBuilder.addParameter(paramSpec)
        }

        // Generate function body with proper required parameters
        val body = when (function.name) {
            "Box" -> "${function.name}(modifier = Modifier, content = { })"
            "Column" -> "${function.name}(modifier = Modifier, verticalArrangement = Arrangement.Top, horizontalAlignment = Alignment.Start, content = { })"
            "Row" -> "${function.name}(modifier = Modifier, horizontalArrangement = Arrangement.Start, verticalAlignment = Alignment.Top, content = { })"
            "Spacer" -> "${function.name}(modifier = Modifier)"
            else -> {
                val parameterNames = function.parameters.joinToString(", ") { param ->
                    if (param.type.contains("Scope.() -> Unit") || param.type.contains("-> Unit")) {
                        "${param.name} = ${param.name}"
                    } else {
                        param.name
                    }
                }
                "${function.name}($parameterNames)"
            }
        }
        funBuilder.addStatement(body)

        return funBuilder.build()
    }

    private fun buildParameterSpec(param: ComposableFunction.Parameter): ParameterSpec {
        val typeName = resolveTypeName(param.type, param.name)
        val paramBuilder = ParameterSpec.builder(param.name, typeName)

        // Add default value if present
        if (param.hasDefault && param.defaultValue != null) {
            paramBuilder.defaultValue(param.defaultValue)
        }

        return paramBuilder.build()
    }

    /**
     * Resolves a type string to a KotlinPoet TypeName.
     */
    private fun resolveTypeName(type: String, paramName: String): TypeName {
        return when {
            type == "Modifier" -> modifierClassName
            type == "Dp" -> dpClassName
            type == "Color" -> colorClassName
            type == "Shape" -> shapeClassName
            type == "Arrangement" -> arrangementClassName
            type == "Arrangement.Horizontal" -> com.squareup.kotlinpoet.ClassName("androidx.compose.foundation.layout", "Arrangement", "Horizontal")
            type == "Arrangement.Vertical" -> com.squareup.kotlinpoet.ClassName("androidx.compose.foundation.layout", "Arrangement", "Vertical")
            type == "Alignment" -> alignmentClassName
            type == "Alignment.Horizontal" -> com.squareup.kotlinpoet.ClassName("androidx.compose.ui", "Alignment", "Horizontal")
            type == "Alignment.Vertical" -> com.squareup.kotlinpoet.ClassName("androidx.compose.ui", "Alignment", "Vertical")
            type == "PaddingValues" -> paddingValuesClassName
            type == "TextStyle" -> textStyleClassName
            type == "FontWeight" -> fontWeightClassName
            type == "TextUnit" -> textUnitClassName
            type == "Painter" -> painterClassName
            type == "ImageVector" -> imageVectorClassName
            type == "Float" -> Float::class.asTypeName()
            type == "Int" -> Int::class.asTypeName()
            type == "Double" -> Double::class.asTypeName()
            type == "Boolean" -> Boolean::class.asTypeName()
            type == "String" -> String::class.asTypeName()
            type == "Long" -> Long::class.asTypeName()
            type.contains("Scope.() -> Unit") || type.contains("-> Unit") -> {
                // Lambda type - use LambdaTypeName
                com.squareup.kotlinpoet.LambdaTypeName.get(returnType = Unit::class.asTypeName())
            }
            else -> {
                // For unknown types, try to use as-is
                if (type.contains(".")) {
                    val parts = type.split(".")
                    val packageName = parts.dropLast(1).joinToString(".")
                    val className = parts.last()
                    com.squareup.kotlinpoet.ClassName(packageName, className)
                } else {
                    // Fallback to Any for truly unknown types
                    com.squareup.kotlinpoet.ClassName("kotlin", "Any")
                }
            }
        }
    }

    /**
     * Returns naming statistics for debugging/diagnostics.
     */
    fun getNamingStatistics(): HybridNamingEngine.NamingStatistics {
        return namingEngine.getStatistics()
    }
}
