package com.acacia.generator

import com.squareup.kotlinpoet.*
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import java.io.File

/**
 * Generates Acacia DSL wrapper code from parsed Modifier function data.
 * Uses JSON output as source of truth for generation with KotlinPoet for type safety.
 */
class DslCodeGenerator {

    private val json = Json {
        ignoreUnknownKeys = true
        prettyPrint = true
    }

    /**
     * Generates DSL wrapper files from the JSON report.
     */
    fun generateFromJson(jsonFile: File, outputDir: File) {
        if (!jsonFile.exists()) {
            throw IllegalStateException("JSON file not found: ${jsonFile.absolutePath}")
        }

        val jsonData = json.decodeFromString<ModifierFunctionsJson>(jsonFile.readText())
        
        outputDir.mkdirs()
        
        // Group functions by package for organized file structure
        val functionsByPackage = jsonData.functions.groupBy { it.package_name }
        
        functionsByPackage.forEach { (packageName, functions) ->
            generateFileForPackage(packageName, functions, outputDir)
        }
        
        // Generate main entry point
        generateMainDslFile(jsonData.functions, outputDir)
    }

    /**
     * Generates a Kotlin file for functions from a specific package.
     */
    private fun generateFileForPackage(
        packageName: String, 
        functions: List<FunctionJson>, 
        outputDir: File
    ) {
        val fileName = packageName.substringAfterLast(".") + "Modifiers.kt"
        
        val fileBuilder = FileSpec.builder("com.acacia.dsl.generated", fileName)
            .addFileComment("Auto-generated by Acacia Plugin - DO NOT EDIT")
            .addFileComment("Source: $packageName")
            .addFileComment("Generated: ${System.currentTimeMillis()}")
        
        // Collect and add imports
        val imports = collectImports(functions)
        imports.sorted().forEach { import ->
            fileBuilder.addImport(import.substringBeforeLast("."), import.substringAfterLast("."))
        }
        
        // Generate each function
        functions.forEach { fn ->
            val funcSpec = generateFunctionSpec(fn)
            fileBuilder.addFunction(funcSpec)
        }
        
        fileBuilder.build().writeTo(outputDir.parentFile) // Write to parent since builder adds package dirs
    }

    /**
     * Generates the main DSL entry point file.
     */
    private fun generateMainDslFile(functions: List<FunctionJson>, outputDir: File) {
        val fileBuilder = FileSpec.builder("com.acacia.dsl.generated", "AcaciaDsl.kt")
            .addFileComment("Auto-generated by Acacia Plugin - DO NOT EDIT")
            .addImport("androidx.compose.ui", "Modifier")
        
        // Create object with shorthand properties
        val objectBuilder = TypeSpec.objectBuilder("AcaciaDsl")
            .addKdoc("Acacia DSL - Concise wrappers for Compose Modifier functions\nTotal functions: ${functions.size}")
        
        // Create shorthand references to all generated functions (limit for demo)
        functions.take(20).forEach { fn ->
            val propSpec = PropertySpec.builder(fn.function_name, LambdaTypeName.get(
                parameters = arrayOf(ParameterSpec.unnamed(ClassName("androidx.compose.ui", "Modifier"))),
                returnType = ClassName("androidx.compose.ui", "Modifier")
            ))
                .addKdoc("Shorthand for [${fn.function_name}]\nPackage: ${fn.package_name}")
                .initializer("{ mod -> mod }")
                .build()
            objectBuilder.addProperty(propSpec)
        }
        
        fileBuilder.addType(objectBuilder.build())
        fileBuilder.build().writeTo(outputDir.parentFile)
    }

    /**
     * Generates a KotlinPoet FunSpec for a single function wrapper.
     */
    private fun generateFunctionSpec(fn: FunctionJson): FunSpec {
        val acaciaName = createAcaciaName(fn.function_name)
        val funcBuilder = FunSpec.builder(acaciaName)
            .addKdoc(buildString {
                appendLine("Acacia wrapper for [${fn.function_name}]")
                appendLine("Original package: ${fn.package_name}")
                appendLine("Module: ${fn.module}")
                if (fn.annotations.isNotEmpty()) {
                    appendLine("Annotations: ${fn.annotations.joinToString(", ")}")
                }
            })
        
        // Set receiver if extension function
        if (fn.extension_class != "none") {
            val receiverType = parseTypeName(fn.extension_class)
            funcBuilder.receiver(receiverType)
        }
        
        // Set return type
        funcBuilder.returns(parseTypeName(fn.return_type))
        
        // Add parameters
        fn.parameters.forEach { param ->
            val paramType = parseTypeName(param.type)
            // Sanitize parameter name to avoid KotlinPoet escaping issues
            val sanitizedName = sanitizeParameterName(param.name)
            val paramSpecBuilder = ParameterSpec.builder(sanitizedName, paramType)
            
            // Add default value if available
            if (param.has_default_value && param.default_value != null) {
                paramSpecBuilder.defaultValue(param.default_value)
            }
            
            funcBuilder.addParameter(paramSpecBuilder.build())
        }
        
        // Build function body - delegate to original
        val delegationBuilder = CodeBlock.builder()
            .addStatement("// TODO: Implement Acacia DSL wrapper logic")
            .addStatement("// Delegate to original: ${fn.package_name}.${fn.function_name}")
        
        // Build the delegation call
        val argList = fn.parameters.joinToString(", ") { sanitizeParameterName(it.name) }
        if (fn.extension_class != "none") {
            delegationBuilder.addStatement("return·this.${fn.function_name}($argList)")
        } else {
            delegationBuilder.addStatement("return·${fn.function_name}($argList)")
        }
        
        funcBuilder.addCode(delegationBuilder.build())
        
        return funcBuilder.build()
    }

    /**
     * Parses a type string into a KotlinPoet TypeName.
     * Simplified to avoid function type parsing issues.
     */
    private fun parseTypeName(typeString: String): TypeName {
        // Handle nullable types
        val isNullable = typeString.endsWith("?")
        val baseType = if (isNullable) typeString.dropLast(1) else typeString
        
        // For function types, use generic FunctionN to avoid escaping issues
        if (baseType.contains("->")) {
            return ClassName("kotlin", "Function1") // Default to Function1 for simplicity
        }
        
        // Handle regular class types
        return when {
            baseType == "kotlin.Unit" || baseType == "Unit" -> if (isNullable) UNIT.copy(nullable = true) else UNIT
            baseType == "kotlin.Boolean" || baseType == "Boolean" -> if (isNullable) BOOLEAN.copy(nullable = true) else BOOLEAN
            baseType == "kotlin.Int" || baseType == "Int" -> if (isNullable) INT.copy(nullable = true) else INT
            baseType == "kotlin.Long" || baseType == "Long" -> if (isNullable) LONG.copy(nullable = true) else LONG
            baseType == "kotlin.Float" || baseType == "Float" -> if (isNullable) FLOAT.copy(nullable = true) else FLOAT
            baseType == "kotlin.Double" || baseType == "Double" -> if (isNullable) DOUBLE.copy(nullable = true) else DOUBLE
            baseType == "kotlin.String" || baseType == "String" -> if (isNullable) STRING.copy(nullable = true) else STRING
            baseType == "kotlin.Any" || baseType == "Any" -> if (isNullable) ANY.copy(nullable = true) else ANY
            baseType.contains(".") -> {
                val packageName = baseType.substringBeforeLast(".")
                val className = baseType.substringAfterLast(".")
                if (packageName.isEmpty() || className.isEmpty()) {
                    ANY
                } else {
                    val classNameObj = ClassName(packageName, className)
                    if (isNullable) classNameObj.copy(nullable = true) else classNameObj
                }
            }
            else -> {
                val classNameObj = ClassName("kotlin", baseType)
                if (isNullable) classNameObj.copy(nullable = true) else classNameObj
            }
        }
    }

    /**
     * Parses a function type string like "Density.() -> IntOffset" or "(A, B) -> C".
     * Simplified to avoid KotlinPoet escaping issues.
     */
    private fun parseFunctionType(typeString: String, isNullable: Boolean): TypeName {
        // For now, treat all function types as generic FunctionN to avoid escaping issues
        // This maintains compilation while we can improve type resolution later
        return when {
            typeString.contains("->") -> {
                // Count parameters by counting commas + 1
                val paramCount = typeString.split(",").size
                val functionN = when (paramCount) {
                    0 -> "kotlin.Function0"
                    1 -> "kotlin.Function1"
                    2 -> "kotlin.Function2"
                    3 -> "kotlin.Function3"
                    else -> "kotlin.FunctionN"
                }
                ClassName("kotlin", functionN.substringAfterLast("."))
            }
            else -> ANY
        }
    }

    /**
     * Collects all imports needed for a set of functions.
     * Simplified to avoid function type parsing issues.
     */
    private fun collectImports(functions: List<FunctionJson>): Set<String> {
        val imports = mutableSetOf<String>()
        
        functions.forEach { fn ->
            // Add receiver type import (skip function types)
            if (fn.extension_class_full != "none" && fn.extension_class_full.contains(".") 
                && !fn.extension_class_full.startsWith("kotlin.")
                && !fn.extension_class_full.contains("->")) {
                imports.add(fn.extension_class_full)
            }
            
            // Add return type import (skip function types)
            if (fn.return_type_full.contains(".") && !fn.return_type_full.startsWith("kotlin.")
                && !fn.return_type_full.contains("->")) {
                imports.add(fn.return_type_full)
            }
            
            // Add parameter type imports (skip function types)
            fn.parameters.forEach { param ->
                val typeFull = param.type_full
                if (typeFull.contains(".") && !typeFull.startsWith("kotlin.")
                    && !typeFull.contains("->")) {
                    // Extract base type without nullability or generics
                    val baseType = typeFull.substringBefore("?").substringBefore("<").substringBefore("(")
                    if (baseType.contains(".")) {
                        imports.add(baseType)
                    }
                }
            }
        }
        
        return imports.filter { it.isNotBlank() }.toSet()
    }

    /**
     * Extracts all class types from a type signature (including function types).
     */
    private fun extractTypesFromSignature(typeSignature: String): List<String> {
        val types = mutableListOf<String>()
        
        // Handle function types
        if (typeSignature.contains("->")) {
            val arrowIndex = typeSignature.lastIndexOf("->")
            val paramsPart = typeSignature.substring(0, arrowIndex).trim()
            val returnPart = typeSignature.substring(arrowIndex + 2).trim()
            
            // Extract receiver if present
            if (paramsPart.endsWith(".") || paramsPart.endsWith("()")) {
                val receiver = paramsPart.removeSuffix(".").removeSuffix("()").trim()
                types.add(receiver)
            } else if (paramsPart.startsWith("(") && paramsPart.endsWith(")")) {
                // Extract from parameter list
                val paramsContent = paramsPart.substring(1, paramsPart.length - 1)
                if (paramsContent.isNotBlank()) {
                    paramsContent.split(", ").forEach { types.add(it.trim()) }
                }
            } else {
                types.add(paramsPart)
            }
            
            types.add(returnPart)
        } else {
            types.add(typeSignature)
        }
        
        return types.map { it.removeSuffix("?") }
    }

    /**
     * Creates Acacia DSL name by prefixing with ac_.
     * e.g., padding -> ac_padding
     */
    private fun createAcaciaName(functionName: String): String {
        return "ac_$functionName"
    }
    
    /**
     * Sanitizes parameter names to avoid KotlinPoet escaping issues.
     * Replaces problematic characters with safe alternatives.
     */
    private fun sanitizeParameterName(name: String): String {
        return name.replace("->", "_to_")
                 .replace("<", "_lt_")
                 .replace(">", "_gt_")
                 .replace("(", "_")
                 .replace(")", "_")
                 .replace("[", "_")
                 .replace("]", "_")
                 .replace("{", "_")
                 .replace("}", "_")
                 .replace(" ", "_")
                 .replace(".", "_")
                 .replace(",", "_")
    }
}

// JSON data classes for reading the generated JSON
@Serializable
data class ModifierFunctionsJson(
    val total_count: Int,
    val generated_at: String,
    val functions: List<FunctionJson>
)

@Serializable
data class FunctionJson(
    val function_name: String,
    val extension_class: String,
    val extension_class_full: String,
    val return_type: String,
    val return_type_full: String,
    val package_name: String,
    val module: String,
    val source: String,
    val annotations: List<String>,
    val parameters: List<ParameterJson>
)

@Serializable
data class ParameterJson(
    val name: String,
    val type: String,
    val type_full: String,
    val has_default_value: Boolean,
    val default_value: String?
)
