package com.acacia.generator

import com.acacia.model.ModifierFunction
import java.io.File

/**
 * Generates Kotlin code for short DSL functions using manual string generation.
 */
class KotlinGenerator {
    
    /**
     * Generates the ShortModifiers.kt file containing all short DSL functions.
     */
    fun generateShortModifiers(
        functions: List<ModifierFunction>,
        outputDir: File,
        nameMappings: Map<String, String> = emptyMap()
    ): File {
        val code = buildKotlinCode(functions, nameMappings)
        
        outputDir.mkdirs()
        val file = File(outputDir, "ShortModifiers.kt")
        file.writeText(code)
        
        return file
    }
    
    private fun buildKotlinCode(functions: List<ModifierFunction>, nameMappings: Map<String, String>): String {
        return buildString {
            appendLine("// Generated by Acacia Shortify Plugin")
            appendLine("// DO NOT EDIT - This file is generated automatically")
            appendLine()
            appendLine("package com.acacia.generated")
            appendLine()
            appendLine("import androidx.compose.ui.Modifier")
            appendLine("import androidx.compose.ui.graphics.Color")
            appendLine("import androidx.compose.ui.unit.Dp")
            appendLine()
            
            functions.sortedBy { it.name }.forEach { function ->
                val shortName = nameMappings[function.name] ?: getShortName(function.name)
                appendLine()
                appendLine("/**")
                appendLine(" * Short DSL function for [Modifier.${function.name}]")
                appendLine(" */")
                appendLine("fun Modifier.$shortName(")
                
                // Add parameters
                function.parameters.forEachIndexed { index, param ->
                    val isLast = index == function.parameters.size - 1
                    val comma = if (isLast) "" else ","
                    appendLine("    ${param.name}: ${param.type}$comma")
                }
                
                appendLine("): Modifier {")
                
                // Generate function body
                val parameterNames = function.parameters.joinToString(", ") { it.name }
                appendLine("    return this.${function.name}($parameterNames)")
                appendLine("}")
            }
        }
    }
    
    /**
     * Maps original function names to short DSL names
     */
    fun getShortName(originalName: String): String {
        return when (originalName) {
            "padding" -> "p"
            "background" -> "bg"
            "fillMaxWidth" -> "fmw"
            "paddingHorizontal" -> "ph"
            "paddingVertical" -> "pv"
            "fillMaxHeight" -> "fmh"
            "size" -> "sz"
            "width" -> "w"
            "height" -> "h"
            "clip" -> "cp"
            "border" -> "br"
            "shadow" -> "sh"
            "clickable" -> "clk"
            else -> {
                // For unknown functions, create a reasonable abbreviation
                if (originalName.length <= 3) {
                    originalName
                } else {
                    // Take first character and last character
                    originalName.first().lowercase() + originalName.last().lowercase()
                }
            }
        }
    }
}
