package com.acacia.generator

import com.acacia.model.ModifierFunction
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.asTypeName
import java.io.File

/**
 * Generates Kotlin code for short DSL functions using KotlinPoet for type-safety.
 */
class KotlinGenerator {

    // Type references for Compose types
    private val modifierClassName = ClassName("androidx.compose.ui", "Modifier")
    private val dpClassName = ClassName("androidx.compose.ui.unit", "Dp")
    private val colorClassName = ClassName("androidx.compose.ui.graphics", "Color")
    private val shapeClassName = ClassName("androidx.compose.ui.graphics", "Shape")
    private val brushClassName = ClassName("androidx.compose.ui.graphics", "Brush")
    private val arrangementClassName = ClassName("androidx.compose.foundation.layout", "Arrangement")
    private val alignmentClassName = ClassName("androidx.compose.ui", "Alignment")
    private val borderStrokeClassName = ClassName("androidx.compose.foundation", "BorderStroke")
    private val dpOffsetClassName = ClassName("androidx.compose.ui.unit", "DpOffset")
    private val offsetClassName = ClassName("androidx.compose.ui.geometry", "Offset")
    private val textUnitClassName = ClassName("androidx.compose.ui.unit", "TextUnit")
    private val fontWeightClassName = ClassName("androidx.compose.ui.text.font", "FontWeight")
    private val textStyleClassName = ClassName("androidx.compose.ui.text", "TextStyle")
    private val imageVectorClassName = ClassName("androidx.compose.ui.graphics.vector", "ImageVector")
    private val painterClassName = ClassName("androidx.compose.ui.graphics.painter", "Painter")

    /**
     * Generates the ShortModifiers.kt file containing all short DSL functions.
     */
    fun generateShortModifiers(
        functions: List<ModifierFunction>,
        outputDir: File,
        nameMappings: Map<String, String> = emptyMap()
    ): File {
        val fileSpec = buildFileSpec(functions, nameMappings)

        outputDir.mkdirs()
        val file = File(outputDir, "ShortModifiers.kt")
        file.writeText(fileSpec.toString())

        return file
    }

    private fun buildFileSpec(functions: List<ModifierFunction>, nameMappings: Map<String, String>): FileSpec {
        val fileBuilder = FileSpec.builder("com.acacia.generated", "ShortModifiers")
            .addFileComment("Generated by Acacia Shortify Plugin")
            .addFileComment("\nDO NOT EDIT - This file is generated automatically")

        // Add imports for commonly used types
        fileBuilder.addImport("androidx.compose.ui", "Modifier")
        fileBuilder.addImport("androidx.compose.ui.unit", "Dp")
        fileBuilder.addImport("androidx.compose.ui.graphics", "Color")

        // Generate functions sorted by name for determinism
        functions.sortedBy { it.name }.forEach { function ->
            val shortName = nameMappings[function.name] ?: getShortName(function.name)
            val funSpec = buildFunctionSpec(function, shortName)
            fileBuilder.addFunction(funSpec)
        }

        return fileBuilder.build()
    }

    private fun buildFunctionSpec(function: ModifierFunction, shortName: String): FunSpec {
        val funBuilder = FunSpec.builder(shortName)
            .receiver(modifierClassName)
            .returns(modifierClassName)
            .addKdoc("Short DSL function for [Modifier.${function.name}]")

        // Add parameters
        function.parameters.forEach { param ->
            val paramSpec = buildParameterSpec(param)
            funBuilder.addParameter(paramSpec)
        }

        // Generate function body
        val parameterNames = function.parameters.joinToString(", ") { it.name }
        funBuilder.addStatement("return this.%N(%L)", function.name, parameterNames)

        return funBuilder.build()
    }

    private fun buildParameterSpec(param: ModifierFunction.Parameter): ParameterSpec {
        val typeName = resolveTypeName(param.type)
        val paramBuilder = ParameterSpec.builder(param.name, typeName)

        // Add default value if present
        if (param.hasDefault && param.defaultValue != null) {
            paramBuilder.defaultValue(param.defaultValue)
        }

        return paramBuilder.build()
    }

    /**
     * Resolves a type string to a KotlinPoet TypeName.
     */
    private fun resolveTypeName(type: String): TypeName {
        return when (type) {
            "Dp" -> dpClassName
            "Color" -> colorClassName
            "Shape" -> shapeClassName
            "Brush" -> brushClassName
            "Arrangement" -> arrangementClassName
            "Alignment" -> alignmentClassName
            "BorderStroke" -> borderStrokeClassName
            "DpOffset" -> dpOffsetClassName
            "Offset" -> offsetClassName
            "Float" -> Float::class.asTypeName()
            "Int" -> Int::class.asTypeName()
            "Double" -> Double::class.asTypeName()
            "Boolean" -> Boolean::class.asTypeName()
            "String" -> String::class.asTypeName()
            "TextUnit" -> textUnitClassName
            "FontWeight" -> fontWeightClassName
            "TextStyle" -> textStyleClassName
            "ImageVector" -> imageVectorClassName
            "Painter" -> painterClassName
            else -> {
                // For unknown types, use dynamic ClassName if it looks like a class reference
                if (type.contains(".")) {
                    val parts = type.split(".")
                    val packageName = parts.dropLast(1).joinToString(".")
                    val className = parts.last()
                    ClassName(packageName, className)
                } else {
                    // Fallback to Any for truly unknown types
                    ClassName("kotlin", "Any")
                }
            }
        }
    }

    /**
     * Maps original function names to short DSL names
     */
    fun getShortName(originalName: String): String {
        return when (originalName) {
            "padding" -> "p"
            "background" -> "bg"
            "fillMaxWidth" -> "fmw"
            "paddingHorizontal" -> "ph"
            "paddingVertical" -> "pv"
            "fillMaxHeight" -> "fmh"
            "size" -> "sz"
            "width" -> "w"
            "height" -> "h"
            "clip" -> "cp"
            "border" -> "br"
            "shadow" -> "sh"
            "clickable" -> "clk"
            else -> {
                // For unknown functions, create a reasonable abbreviation
                if (originalName.length <= 3) {
                    originalName
                } else {
                    // Take first character and last character
                    originalName.first().lowercase() + originalName.last().lowercase()
                }
            }
        }
    }
}
