package com.acacia.generator

import com.acacia.model.ModifierFunction
import com.squareup.kotlinpoet.*
import java.io.File

/**
 * Generates Kotlin code for short DSL functions using KotlinPoet.
 */
class KotlinGenerator {
    
    /**
     * Generates the ShortModifiers.kt file containing all short DSL functions.
     */
    fun generateShortModifiers(
        functions: List<ModifierFunction>,
        outputDir: File,
        nameMappings: Map<String, String> = emptyMap()
    ): File {
        val fileSpec = buildFileSpec(functions, nameMappings)
        
        outputDir.mkdirs()
        fileSpec.writeTo(outputDir)
        
        return File(outputDir, "ShortModifiers.kt")
    }
    
    private fun buildFileSpec(functions: List<ModifierFunction>, nameMappings: Map<String, String>): FileSpec {
        return FileSpec.builder("com.acacia.generated", "ShortModifiers")
            .addFileComment("Generated by Acacia Shortify Plugin")
            .addFileComment("DO NOT EDIT - This file is generated automatically")
            .apply {
                functions.sortedBy { it.name }.forEach { function ->
                    addFunction(buildFunction(function, nameMappings))
                }
            }
            .build()
    }
    
    private fun buildFunction(function: ModifierFunction, nameMappings: Map<String, String>): FunSpec {
        val shortName = nameMappings[function.name] ?: getShortName(function.name)
        
        return FunSpec.builder(shortName)
            .receiver(ClassName("androidx.compose.ui", "Modifier"))
            .returns(ClassName("androidx.compose.ui", "Modifier"))
            .addKdoc("Short DSL function for [Modifier.${function.name}]")
            .apply {
                // Add parameters
                function.parameters.forEach { param ->
                    val parameterSpec = ParameterSpec.builder(
                        name = param.name,
                        type = parseTypeName(param.type)
                    ).apply {
                        if (param.hasDefault && param.defaultValue != null) {
                            defaultValue(param.defaultValue)
                        }
                    }.build()
                    addParameter(parameterSpec)
                }
                
                // Generate function body
                val parameterNames = function.parameters.joinToString(", ") { it.name }
                addStatement("return this.%L(%L)", function.name, parameterNames)
            }
            .build()
    }
    
    /**
     * Maps original function names to short DSL names
     */
    fun getShortName(originalName: String): String {
        return when (originalName) {
            "padding" -> "p"
            "background" -> "bg"
            "fillMaxWidth" -> "fmw"
            "paddingHorizontal" -> "ph"
            "paddingVertical" -> "pv"
            "fillMaxHeight" -> "fmh"
            "size" -> "sz"
            "width" -> "w"
            "height" -> "h"
            "clip" -> "cp"
            "border" -> "br"
            "shadow" -> "sh"
            "clickable" -> "clk"
            else -> {
                // For unknown functions, create a reasonable abbreviation
                if (originalName.length <= 3) {
                    originalName
                } else {
                    // Take first character and last character
                    originalName.first().lowercase() + originalName.last().lowercase()
                }
            }
        }
    }
    
    private fun parseTypeName(type: String): TypeName {
        return when (type) {
            "Dp" -> ClassName("androidx.compose.ui.unit", "Dp")
            "Color" -> ClassName("androidx.compose.ui.graphics", "Color")
            "Boolean" -> ClassName("kotlin", "Boolean")
            "Int" -> ClassName("kotlin", "Int")
            "Float" -> ClassName("kotlin", "Float")
            "String" -> ClassName("kotlin", "String")
            else -> {
                // Try to parse as simple class name
                val parts = type.split(".")
                if (parts.size == 1) {
                    ClassName("", type)
                } else {
                    ClassName(parts.dropLast(1).joinToString("."), parts.last())
                }
            }
        }
    }
}
