package com.acacia.generator

import com.acacia.mapping.GoldenMappings
import com.acacia.mapping.HybridNamingEngine
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.TypeAliasSpec
import java.io.File

/**
 * Generates short type aliases for common Compose types.
 * 
 * Examples:
 * - typealias Cl = Color
 * - typealias D = Dp
 * - typealias Sh = Shape
 * - typealias Arr = Arrangement
 * - typealias Al = Alignment
 */
class TypeAliasGenerator {

    private val namingEngine = HybridNamingEngine()

    // Type alias definitions (target type to package mapping)
    private val typeAliasDefinitions = listOf(
        // Colors & Graphics
        TypeAliasDef("Color", "androidx.compose.ui.graphics", "Color"),
        TypeAliasDef("Shape", "androidx.compose.ui.graphics", "Shape"),
        TypeAliasDef("Brush", "androidx.compose.ui.graphics", "Brush"),
        TypeAliasDef("ImageVector", "androidx.compose.ui.graphics.vector", "ImageVector"),
        TypeAliasDef("Painter", "androidx.compose.ui.graphics.painter", "Painter"),
        
        // Units & Geometry
        TypeAliasDef("Dp", "androidx.compose.ui.unit", "Dp"),
        TypeAliasDef("TextUnit", "androidx.compose.ui.unit", "TextUnit"),
        TypeAliasDef("DpOffset", "androidx.compose.ui.unit", "DpOffset"),
        TypeAliasDef("Offset", "androidx.compose.ui.geometry", "Offset"),
        
        // Layout & Arrangement
        TypeAliasDef("Arrangement", "androidx.compose.foundation.layout", "Arrangement"),
        TypeAliasDef("Alignment", "androidx.compose.ui", "Alignment"),
        
        // Foundation
        TypeAliasDef("BorderStroke", "androidx.compose.foundation", "BorderStroke"),
        
        // Text & Typography
        TypeAliasDef("TextStyle", "androidx.compose.ui.text", "TextStyle"),
        TypeAliasDef("FontWeight", "androidx.compose.ui.text.font", "FontWeight"),
        
        // Modifiers (the Modifier type itself)
        TypeAliasDef("Modifier", "androidx.compose.ui", "Modifier"),
        
        // Common lambda types
        TypeAliasDef("ModifierScope", "androidx.compose.ui", "Modifier.Companion"),
    )

    data class TypeAliasDef(
        val shortName: String,
        val packageName: String,
        val typeName: String
    )

    /**
     * Generates the ShortTypeAliases.kt file.
     */
    fun generateTypeAliases(outputDir: File): File {
        val fileSpec = buildFileSpec()

        val outputFile = File(outputDir, "ShortTypeAliases.kt")
        outputFile.parentFile.mkdirs()

        fileSpec.writeTo(outputFile.parentFile.toPath())

        return outputFile
    }

    private fun buildFileSpec(): FileSpec {
        val fileBuilder = FileSpec.builder("com.acacia.generated", "ShortTypeAliases")
            .addFileComment(
                "Auto-generated short type aliases for Compose types.\n" +
                "Generated by Acacia Shortify Plugin.\n" +
                "DO NOT EDIT - This file will be regenerated on each build.\n\n" +
                "Examples:\n" +
                "- Cl = Color\n" +
                "- D = Dp\n" +
                "- Sh = Shape\n" +
                "- Arr = Arrangement\n" +
                "- Al = Alignment\n"
            )

        // Build type aliases sorted for determinism
        typeAliasDefinitions.sortedBy { it.shortName }.forEach { def ->
            val targetTypeName = ClassName(def.packageName, def.typeName)
            
            val typeAliasSpec = TypeAliasSpec.builder(def.shortName, targetTypeName)
                .addModifiers(KModifier.PUBLIC)
                .build()
            
            fileBuilder.addTypeAlias(typeAliasSpec)
        }

        return fileBuilder.build()
    }

    /**
     * Generates type aliases as raw content (more control than KotlinPoet for this case).
     */
    fun generateTypeAliasesRaw(outputDir: File): File {
        val outputFile = File(outputDir, "ShortTypeAliases.kt")
        outputFile.parentFile.mkdirs()

        val content = buildString {
            appendLine("package com.acacia.generated")
            appendLine()
            appendLine("import androidx.compose.ui.Modifier")
            appendLine("import androidx.compose.ui.Alignment")
            appendLine("import androidx.compose.ui.graphics.Color")
            appendLine("import androidx.compose.ui.graphics.Shape")
            appendLine("import androidx.compose.ui.graphics.Brush")
            appendLine("import androidx.compose.ui.graphics.vector.ImageVector")
            appendLine("import androidx.compose.ui.graphics.painter.Painter")
            appendLine("import androidx.compose.ui.unit.Dp")
            appendLine("import androidx.compose.ui.unit.TextUnit")
            appendLine("import androidx.compose.ui.unit.DpOffset")
            appendLine("import androidx.compose.ui.geometry.Offset")
            appendLine("import androidx.compose.foundation.layout.Arrangement")
            appendLine("import androidx.compose.foundation.BorderStroke")
            appendLine("import androidx.compose.ui.text.TextStyle")
            appendLine("import androidx.compose.ui.text.font.FontWeight")
            appendLine()
            appendLine("// Auto-generated short type aliases for Compose types")
            appendLine("// DO NOT EDIT - Generated by Acacia Shortify Plugin")
            appendLine()
            
            // Colors & Graphics
            appendLine("/** Short type alias for [Color] */")
            appendLine("typealias Cl = Color")
            appendLine()
            appendLine("/** Short type alias for [Shape] */")
            appendLine("typealias Sh = Shape")
            appendLine()
            appendLine("/** Short type alias for [Brush] */")
            appendLine("typealias Br = Brush")
            appendLine()
            appendLine("/** Short type alias for [ImageVector] */")
            appendLine("typealias IV = ImageVector")
            appendLine()
            appendLine("/** Short type alias for [Painter] */")
            appendLine("typealias Pn = Painter")
            appendLine()
            
            // Units & Geometry
            appendLine("/** Short type alias for [Dp] */")
            appendLine("typealias D = Dp")
            appendLine()
            appendLine("/** Short type alias for [TextUnit] */")
            appendLine("typealias TU = TextUnit")
            appendLine()
            appendLine("/** Short type alias for [DpOffset] */")
            appendLine("typealias DO = DpOffset")
            appendLine()
            appendLine("/** Short type alias for [Offset] */")
            appendLine("typealias O = Offset")
            appendLine()
            
            // Layout & Arrangement
            appendLine("/** Short type alias for [Arrangement] */")
            appendLine("typealias Arr = Arrangement")
            appendLine()
            appendLine("/** Short type alias for [Alignment] */")
            appendLine("typealias Al = Alignment")
            appendLine()
            
            // Foundation
            appendLine("/** Short type alias for [BorderStroke] */")
            appendLine("typealias BS = BorderStroke")
            appendLine()
            
            // Text & Typography
            appendLine("/** Short type alias for [TextStyle] */")
            appendLine("typealias TS = TextStyle")
            appendLine()
            appendLine("/** Short type alias for [FontWeight] */")
            appendLine("typealias FW = FontWeight")
            appendLine()
            
            // Modifier type
            appendLine("/** Short type alias for [Modifier] */")
            appendLine("typealias M = Modifier")
        }

        outputFile.writeText(content)
        return outputFile
    }
}
